### ISSUE TITLE
AnalyticsConfig.setAppkey()和AnalyticsConfig.setChannel()方法不是公共的不能调用

### ISSUE THREAD

**Issue by IdioticMadman** [chentao0707/SimplifyReader#89]
https://github.com/chentao0707/SimplifyReader/blob/master/app/src/main/java/com/github/obsessive/simplifyreader/ui/activity/SplashActivity.java#L131

![image](https://cloud.githubusercontent.com/assets/16788980/23388768/2dbfeb24-fd9f-11e6-87a9-2e4e65976d3f.png)
![image](https://cloud.githubusercontent.com/assets/16788980/23388827/78f6741e-fd9f-11e6-84f8-789938910fa6.png)

**Comment by 13286810620** [comment]
I have the same question！Hope the writer could resolve it.

**Comment by JerryMissTom** [comment]
应该是友盟的出了问题。

**Comment by chentao0707** [comment]
直接把友盟相关的代码删除就可以了。。。
